### ISSUE TITLE
My name doesn't appear in the copyright information.

### ISSUE THREAD

**Issue by amblerkr** [microfeed/microfeed#103]
https://{mydomain.com}/admin/settings/code-editor/?type=themes&theme=custom#webBodyEnd
![image](https://github.com/microfeed/microfeed/assets/67187038/451795e3-96de-4a46-89a1-06df632c2d2b)

My name doesn't appear in the copyright information.
Only © is displayed. 
If it's displayed properly, it should have the year and your name (nickname).

**Comment by wenbinf** [comment]
Hi @amblerkr -

Let's troubleshoot step by step.

First, could you inspect the "copyright" field in your json feed?

Open {{mydomain.com}}/json and check "copyright" to see if there's any text. For example, here's our json feed https://www.microfeed.org/json and the copyright field looks like this:
<img width="561" alt="Screenshot 2023-10-17 at 10 53 37 AM" src="https://github.com/microfeed/microfeed/assets/1719237/475baf51-b125-4de9-8b1a-3af653643c43">

Second, could you check if you've put any text to copyright on your admin?

It's under /admin/channels/primary/ - 

<img width="803" alt="Screenshot 2023-10-17 at 10 55 07 AM" src="https://github.com/microfeed/microfeed/assets/1719237/2ef5f348-6c54-44f6-9630-3962867330eb">

**Comment by amblerkr** [comment]
I am impressed with your kind response.
It was easy to understand.

I have already hosted a few microfeeds.
I forgot to put a copyright on the last one I hosted.
I fixed it right away after seeing your answer.
