### ISSUE TITLE
Support for Multiple Channels?

### ISSUE THREAD

**Issue by chrisspiegl** [microfeed/microfeed#106]
I am just looking for a Cloudflare stack CMS and found this project.

I am wondering if this system might be expanded to support multiple channels?

This would be useful to for example work with `posts` and `pages`?

Thanks for your consideration and for building this.

**Comment by kenara** [comment]
Hey @chrisspiegl, what do you mean by channels? Content types, or users? 
And please explain `posts` and `pages` - this project is installed as a Cloudflare page. What's a `post`?
More detail might help @wenbinf ... he's a busy guy.

**Comment by chrisspiegl** [comment]
Didn't see the community posts (not used since it doesn't show any activity in the tab bar 🙈).

I found my answer: https://github.com/microfeed/microfeed/discussions/69

What I meant is the ability to create multiple channels of different content types. One could use one for blog posts, one for blog pages, one for podcast episodes, etc…

But for now it appears to be not planed and the workaround would be installing multiple instances of microfeed.
