### ISSUE TITLE
github deploy fails with node.js action error

### ISSUE THREAD

**Issue by hhoffman** [microfeed/microfeed#126]
forked the microfeed to my local repo. Following along with the readme but have run into this error in deploying the action:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by wenbinf** [comment]
"Error InvalidArgument: Invalid Argument: Credential access key has length 39, should be 32"

Could you double check if your r2 api key / secret are correct?

**Comment by hhoffman** [comment]
Thanks, indeed that was it </sigh>
