### ISSUE TITLE
Firefox form issue when updating/creating item

### ISSUE THREAD

**Issue by hailspuds** [microfeed/microfeed#13]
Hello,

When you go into the "add new item" or edit an existing item in Firefox, you get a warning box when you create/update (pages: /admin/items/new/ and /admin/items/xxxxxxxID/)

I'm running version 108.0.1 on OS X - and the same issue doesn't seem to occur in Chrome.

Here's a screenshot of the issue:

<img width="379" alt="Screen Shot 2022-12-30 at 8 29 50 am" src="https://user-images.githubusercontent.com/851118/210013186-e8003bf8-3f92-494f-82b3-c496d134b385.png">

The developer tools console throws a warning saying "Form contains a file input, but is missing method=POST and enctype=multipart/form-data on the form.  The file will not be sent."

It does still save/create the item no matter what you push, so there doesn't seem to be any data loss. 

Thanks!

**Comment by wenbinf** [comment]
Thanks for reporting this issue. 

Confirmed. It's a bug on our end.

Now it should be fixed by https://github.com/microfeed/microfeed/pull/14

Please sync your forked repo & re-deploy the code in GitHub Actions.
