### ISSUE TITLE
Unable to upload media with microfeed Add new item interface

### ISSUE THREAD

**Issue by zoefried** [microfeed/microfeed#144]
Hello, I didn't use my microfeed CMS for over a year, since about February 2023. Now when I try to upload media (for example an mp4 file), I get a CORS error. I worked a lot with ChatGPT for suggestions for how to fix the problem but I have struck out.

I am trying to upload media from the Add new item interface, and it fails every time, regardless of media type (I've tried a video file and an image file).

I AM able to create a new item, just unable to add media to it.

Here is a sample PUT request (this info all comes from Developer Tools in the browser, and I've substituted myprojectname for my actual CloudFlare project name):

PUT https://myprojectname.d004a4e27fd7ccff6d4a04f13cc9d095.r2.cloudflarestorage.com/myprojectname/production/media/video-cc891d42918aa95463035bbd174988a4.mp4?X-Amz-Date=20240717T193530Z&X-Amz-Expires=86400&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=9305e22b846b42cf0a54900579ddcea1/20240717/auto/s3/aws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=009ae326e108843fe9275f9434cbb229545aee742fb8639e115ebcc9a0976fe0

And here is the response:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://myprojectname.d004a4e27fd7ccff6d4a04f13cc9d095.r2.cloudflarestorage.com/myprojectname/production/media/video-cc891d42918aa95463035bbd174988a4.mp4?X-Amz-Date=20240717T193530Z&X-Amz-Expires=86400&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=9305e22b846b42cf0a54900579ddcea1%2F20240717%2Fauto%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=009ae326e108843fe9275f9434cbb229545aee742fb8639e115ebcc9a0976fe0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 401.

Here is the CORS policy for my R2 bucket:
---------
[
  {
    "AllowedOrigins": [
      "*"
    ],
    "AllowedMethods": [
      "DELETE",
      "POST",
      "PUT",
      "GET"
    ],
    "AllowedHeaders": [
      "*"
    ],
    "MaxAgeSeconds": 3000
  }
]
----------

Thanks for any help you can provide.

**Comment by kenara** [comment]
https://chatgpt.com/share/6339e19d-eb13-49b0-a8eb-85d3eb43f640

**Comment by zoefried** [comment]
My mistake that the wildcards I already had did not show. Hopefully they do now, also I added the ExposeHeaders parameter, still getting the same result.

Here is my CORS settings file:

`[
  {
    "AllowedOrigins": [
      "*"
    ],
    "AllowedMethods": [
      "DELETE",
      "POST",
      "PUT",
      "GET"
    ],
    "AllowedHeaders": [
      "*"
    ],
    "ExposeHeaders": [
      "ETag"
    ],
    "MaxAgeSeconds": 3000
  }
]`

**Comment by wenbinf** [comment]
Could you please double-check if your R2 secret keys are still valid? It's possible that an expiry date was set for your old R2 secret keys in the past.

If you need to rotate and generate a new R2 secret key, you will need to re-deploy the project.

**Comment by zoefried** [comment]
After fixing all my incorrect secrets and redeploying microfeed, this is working. Thanks for your help.
