### ISSUE TITLE
Unable to deploy new version of microfeed

### ISSUE THREAD

**Issue by zoefried** [microfeed/microfeed#145]
I can't help feeling this could be related to my issue #144

Before trying to upload new media to my microfeed site, I tried to follow the instructions in https://www.microfeed.org/i/migrating-your-microfeed-instance-from-d1-alpha-to-Asz44We3XZP/

I followed the steps to migrate the database and create the environment secret, but when I try "Re-deploy your Microfeed instance by triggering the deploy GitHub action" I get an error (have tried 3 times).

Here is the error shown in the log, it starts at line 39 of the Setup section:

`

> Error AccessDenied: Access Denied
>     at throwDefaultError (/home/runner/work/microfeed/microfeed/node_modules/@smithy/smithy-client/dist-cjs/index.js:839:20)
>     at /home/runner/work/microfeed/microfeed/node_modules/@smithy/smithy-client/dist-cjs/index.js:848:5
>     at de_CommandError (/home/runner/work/microfeed/microfeed/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4741:14)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async /home/runner/work/microfeed/microfeed/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
>     at async /home/runner/work/microfeed/microfeed/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:226:18
>     at async /home/runner/work/microfeed/microfeed/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
>     at async /home/runner/work/microfeed/microfeed/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:98:20
>     at async /home/runner/work/microfeed/microfeed/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:121:14
>     at async /home/runner/work/microfeed/microfeed/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22 {
>   '$fault': 'client',
>   '$metadata': {
>     httpStatusCode: 403,
>     requestId: undefined,
>     extendedRequestId: undefined,
>     cfId: undefined,
>     attempts: 1,
>     totalRetryDelay: 0
>   },
>   Code: 'AccessDenied'
> }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Error: Process completed with exit code 1.

`

**Comment by wenbinf** [comment]
Looks like api keys are invalid. Please double check if all API keys are correct

```
httpStatusCode: 403,
requestId: undefined,
extendedRequestId: undefined,
cfId: undefined,
attempts: 1,
totalRetryDelay: 0
},
Code: 'AccessDenied'
```

**Comment by zoefried** [comment]
I created a new R2 access key ID and and R2 secret access key and put them in the secrets. I'm still getting a failure. I don't know if I've created them correctly.

One thing I noticed is that this link is broken (https://github.com/microfeed/microfeed/settings/secrets/actions) which maybe used to provide more information about how to create the secrets.

<img width="930" alt="image" src="https://github.com/user-attachments/assets/a948d506-e7d7-46d0-8b43-dc3356518055">

**Comment by zoefried** [comment]
Also not exactly sure what should go in the CLOUDFLARE_PROJECT_NAME secret.

**Comment by wenbinf** [comment]
Please refer to this section for secrets:
https://github.com/microfeed/microfeed?tab=readme-ov-file#step-2-put-some-secrets-on-your-forked-repo

And for CLOUDFLARE_PROJECT_NAME - 
<img width="885" alt="Screenshot 2024-07-17 at 3 30 53 PM" src="https://github.com/user-attachments/assets/67c5f047-1ffd-4643-8027-8eabd8e6cf6f">

**Comment by zoefried** [comment]
Thank you for your patience, I embarrassingly failed to notice the dropdown explanations next to each of the secrets. I had chosen the wrong permissions for the R2 tokens (since I missed the explanations and guessed wrong).
