### ISSUE TITLE
Cloudflare Access protection

### ISSUE THREAD

**Issue by tranqy** [microfeed/microfeed#20]
I attempted to use the original instructions for configuring Cloudflare Access protection but it did not work. 

I have cobbled together protection and wanted to share it here.  I almost updated the documentation but it's a lot to do and wasn't sure it belongs there.

1) Setup a custom domain. 
2) Create a bulk redirect list (if you don't have one)
3) Add a redirect for {microfeed}.pages.dev -> {mirofeed}.tld
4) Setup a cloudflare access rule for {microfeed}.tld/admin

And it's working.  If I open {microfeed}.pages.dev it immediately redirects to the tld, and admin forces auth. 

This setup does require a few additional cloudflare things which is why I paused when updating the readme in my fork. I'd be happy to work on adding this to the docs over the next few days if the team would like.

**Comment by wenbinf** [comment]
@tranqy - thanks for sharing a different way of setting up cloudflare access for the admin dashboard!

Do you remember why the instructions from the dashboard setup checklist didn't work for you? 

<img width="370" alt="Screenshot 2022-12-30 at 9 25 25 PM" src="https://user-images.githubusercontent.com/1719237/210070035-e8e96784-63e8-4250-9dc6-7e7abfb26fe2.png">

We try to minimize the number of Cloudflare products / concepts used by microfeed. So people don't need to learn too many new things before using microfeed :)

**Comment by tranqy** [comment]
Cloudflare did not allow me to create an application for a pages.dev domain.  I could add a rule from the pages app that covers the whole app, but then the path was uneditable. There was no way for me to create the access application as outlined in the docs.

**Comment by wenbinf** [comment]
ah, i know what you mean.

in fact, you can safely ignore cloudflare's error message (something like "this domain doesn't exist"), and go ahead to create a rule for *.pages.dev

i'll report this issue to cloudflare and make it clear in the document / setup checklist .

**Comment by tranqy** [comment]
You're right, I was able to get past that.  One trick, you have to add the folder name before you add the domain name, once the invalid domain name validation is triggered the folder field is disabled.

**Comment by tranqy** [comment]
Closing because the original instructions worked mostly. You may want to clearly document that, I threw like an hour into it.  I can swing at it over the holiday too.

**Comment by wenbinf** [comment]
> You're right, I was able to get past that. One trick, you have to add the folder name before you add the domain name, once the invalid domain name validation is triggered the folder field is disabled.

Glad that it works for you.

Yea, it's certainly something Cloudflare should improve in their dashboard UI :) 

We try to make it clear the sequence of operations in the screenshot (numbers in the screenshot...)- 
<img width="1008" alt="Screenshot 2022-12-31 at 10 10 43 AM" src="https://user-images.githubusercontent.com/1719237/210120627-e1a1c97d-ba5b-4473-8a21-e15854fe516a.png">

But it's not enough. We oftentimes skim the screenshot and ignore details (especially texts) on the image. Ideally, it's one-click to setup, so people don't need to learn new UI & new concepts of Cloudflare before using microfeed. 

Short term, we may add more texts to explain & make it more clearly. 
Long term, we'll try [Cloudflare API](https://api.cloudflare.com/#access-applications-get-an-access-application) to further streamline & automate the onboarding process.
Longer term, we'll try to work with Cloudflare to see if things can move towards a "one-click" onboarding :)

**Comment by tranqy** [comment]
You caught me, I def glossed right over those numbers. Adding a comment like "Make sure to enter the fields in the order specified" could possibly save the next dev from missing that.

Thanks again for the alpha and happy new year!

**Comment by ThomasRedstone** [comment]
I think CloudFlare's UI has been updated, now the domain field self-clears if the entered domain doesn't match one that you have on your account!

**Comment by wenbinf** [comment]
> I think CloudFlare's UI has been updated, now the domain field self-clears if the entered domain doesn't match one that you have on your account!

You have to click on the dropdown to select the domain - 
<img width="621" alt="Screenshot 2023-02-18 at 4 40 46 PM" src="https://user-images.githubusercontent.com/1719237/219905792-4dabbad3-2212-4cd0-9882-5a69ff31b451.png">
