### ISSUE TITLE
Bookmarklet: add a "to microfeed" issues

### ISSUE THREAD

**Issue by gabbello** [microfeed/microfeed#24]
First of all, great project and very good docs.

There are a couple of small issues with the js code that is presented in Add new item -> external URL,  "Bookmarklet: add a "to microfeed" button to browser".

If I add this code to browser favorites and click on it on some random url I will get redirected to correct admin page  (/admin/items/new/) with the Title and URL prefilled correctly however the Create button is not active. 
It seems that if I put focus in any field (description, link, etc) and add some character the Create button becomes active, but when pressed it actually create a item of type audio, rather than external URL.
Issue happens in both Fireforx and Chrome (on windows 11)

**Comment by wenbinf** [comment]
Thanks for reporting the bug.

This should be fixed by https://github.com/microfeed/microfeed/pull/29

Please sync & redeploy code:
https://github.com/microfeed/microfeed#bonus-update-to-the-latest-version-of-microfeed

**Comment by gabbello** [comment]
fixed confirmed. thanks!
