### ISSUE TITLE
Title without ASCII characters got 404

### ISSUE THREAD

**Issue by matsuu** [microfeed/microfeed#30]
ex: こんにちは、世界 (means Hello World)
![スクリーンショット 2023-01-03 22 58 41](https://user-images.githubusercontent.com/4395/210371857-070aa844-edb3-40aa-b745-6a98d4e4938d.png)
404 error
![スクリーンショット 2023-01-03 23 03 20](https://user-images.githubusercontent.com/4395/210372556-3c4047dc-c004-48da-b2a9-2228a426f977.png)

**Comment by wenbinf** [comment]
@matsuu Thanks for reporting this bug.

It should be fixed by https://github.com/microfeed/microfeed/pull/31

Please sync & redeploy code - 
https://github.com/microfeed/microfeed/tree/v0.1.1#bonus-update-to-the-latest-version-of-microfeed
