### ISSUE TITLE
Cannot upload channel image, CORS issue

### ISSUE THREAD

**Issue by robotnoises** [microfeed/microfeed#32]
Hi there,

I'm getting a CORS error when attempting to change the channel image. Maybe it's something obvious as I'm not super-familiar with Cloudflare R2, but everything else in the checklist seems to be working fine.

<img width="939" alt="Screen Shot 2023-01-03 at 9 46 38 PM" src="https://user-images.githubusercontent.com/5273040/210475237-87e0e08d-5324-45ac-97ed-cb399078652b.png">

This is using a brand new domain I purchased today through Cloudflare.

FWIW, if I upload the image directly to my bucket using the Cloudflare console, I'm able to view the image by going to `media-cdn.my-custom-domain.com/MYIMG.jpeg` just fine.

**Comment by wenbinf** [comment]
with all info i can see from your description, this is my best guess -

it seems to be problems related to expired Cloudflare Access session, not R2 issues

could you try this:

1. refresh the admin page 
2. try again
