### ISSUE TITLE
Cannot create self-hosted app

### ISSUE THREAD

**Issue by cy6erskunk** [microfeed/microfeed#35]
It is not possible to create a self-hosted app when there's no zones configured - the button is completely disabled (which is the case for a first-time user who wants to use a `*.pages.dev` domain). 

However, I could find a workaround: it is possible to do it by going the pages setting page and enabling access policy - and then it's possible to change it to the `admin` path only.

**Comment by wenbinf** [comment]
related issue here :
https://github.com/microfeed/microfeed/issues/20
