### ISSUE TITLE
Settings: Channel description custom html source is overridden by visual editor HTML code

### ISSUE THREAD

**Issue by leecjohnny** [microfeed/microfeed#36]
After entering custom HTML source for the description and clicking update, the custom HTML source successfully updates the page.

However, upon returning the settings page at `/admin/channels/primary/`, the form defaults to selecting "visual editor" and the associated HTML code from the visual editor overrides the previous updated custom HTML source.

Steps to reproduce:
1. Go to `/admin/channels/primary/`, enter some text into description using visual editor. Click update.
2. Refresh the page, select "html source" for description. Enter some HTML edits. Click update.
3. Refresh the page, select "html source" for description. The updates from step 2 will not be present.

**Comment by wenbinf** [comment]
@leecjohnny Thanks for reporting this issue.

I can't re-produce this issue on my end after trying a few times, but I have some hypotheses about what might go wrong -

1)  Did you happen to open two tabs in the browser and the one tab's updates overwrite the other one's?

2) Cloudflare D1 might have bug (or feature?) of read-after-write data inconsistency: Data updates may not propagate fast enough to all data centers, and subsequent reads may still get stale data.

Going forward - 

1) Could you try again on your end to see if this issue persists?

2) We'll keep an eye to see if other people report the same issue.

3) I'll talk to Cloudflare to confirm if there might be read-after-write inconsistency problem for d1. Re: https://github.com/microfeed/microfeed/issues/3

**Comment by leecjohnny** [comment]
Thank you for the quick reply. 

I tried again in Chrome and Safari with only 1 tab open. I think it may have to do with how the quill editor handle state changes for between rich and plaintext. I believe the new value makes it to D1 as expected, it's how the editor behaves with the HTML value.






https://user-images.githubusercontent.com/2618366/211154063-50313c48-75bd-4716-89e6-4d4cd742f258.mp4

**Comment by wenbinf** [comment]
Thanks for providing the screencast. Now it's clear to me what went wrong :)

So it's not related to d1 or any edge-side code. It's how Quill handles & transforms raw html.

Quill tries to be "smart" to remove empty tags - probably we can tweak quill configuration to fix it (TODO).

When you put `<i></i>` in html source, then quill will remove it automatically.
When you put `<i>hello tag</i>` instead, quill will keep it and transform it to `<em>hello tag</em>`.

I'll spend some time research [quill](https://quilljs.com/) configuration / source code a bit to see if we can do something here to fix.

**Comment by wenbinf** [comment]
For the time being, there are two hacks you can use to insert something like `<i class="fa fa-github"></i>`:

1) Use `<i class="fa fa-github" />`


2) Edit raw html for themes directly: /admin/settings/code-editor/?type=themes&theme=custom#webFeed
<img width="976" alt="Screenshot 2023-01-08 at 8 33 06 AM" src="https://user-images.githubusercontent.com/1719237/211174053-4d2528ad-5e50-4f5f-92dc-f0848cfa97c4.png">

In fact, I'd prefer 2). 

For 1), you'll rely on a 3rd-party js/css (fontawesome), which only works for web feed, not for rss/json feed.
For 2), it's web-specific. I guess you only want to display a github icon on web pages, not on the rss feed. Right?

**Comment by leecjohnny** [comment]
Thank you for the suggestion. Yes, I ended up going with 2, as I had to insert the fontawesome css in another part of the theme html anyways. 

Keep up the good work.

**Comment by wenbinf** [comment]
Close this issue as "Won't fix" for now. We may come back to revisit it in the future.

So [QuillJs](https://quilljs.com/) (the library we use for rich editor) proactively clean up html to prevent cross site scripting (XSS). We can get around it and allow all html by using quilljs's [dangerouslyPasteHTML](https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml). As the name suggests, it's "dangerous" :)

We'll need to think through it to make the right trade-offs: 1) security for all users; 2) ease of use for most users; 3) flexibility for tech-savvy power users.
