### ISSUE TITLE
Error In Deploy operation

### ISSUE THREAD

**Issue by AmmarKayali10** [microfeed/microfeed#38]
I get this problem when I tried to deploy the repo to Cloudflare Pages:

![Screenshot_2](https://user-images.githubusercontent.com/122178236/211169592-dbc678ac-87fb-466c-83dd-4d898d7aad31.jpg)

Error InvalidArgument: Invalid Argument: Credential access key has length 34, should be 32

**Comment by jasontally** [comment]
As the error message indicates, check  to be sure your R2 access key ID and secret key are correct.

**Comment by AmmarKayali10** [comment]
> As the error message indicates, check to be sure your R2 access key ID and secret key are correct.

Thank you @jasontally, I removed these keys and re-add them and it was solved, I tried to edit it before but it's not working.
