### ISSUE TITLE
Settings changes are not getting saved

### ISSUE THREAD

**Issue by zoefried** [microfeed/microfeed#48]
I installed microfeed around Feb 1 and was able to make a change to one of the settings on Feb 3 (I added meta og tags to the web header). Today I was trying to make further changes, but the changes don't get saved. For example, if I try to modify one of my meta og tags in the Web Header, and then click Update, the UI shows "Updated" but if I refresh the Settings page I can see the update was not saved, and if I go to Cloudflare D1 I can see the database tables haven't been updated since Feb 3 (to be clear, I haven't tried to work on this between Feb 3 and tonight). How can I troubleshoot the failure to update the database tables? Thanks!

**Comment by zoefried** [comment]
Hi @wenbinf.
Yes I can reproduce this. I can see the tags (because I added them a couple weeks ago) but changes are not saved. I don't see any error messages. Here is a screen recording.

https://user-images.githubusercontent.com/6957655/218551274-33ffbb23-8546-4af1-b0b1-13e32e6393af.mov

**Comment by wenbinf** [comment]
@zoefried - thanks for providing the screencast.

I can confirm that it's a bug in our code. And it's fixed now in https://github.com/microfeed/microfeed/pull/50

Please sync to the latest updates and redeploy the code on your end:

![image](https://user-images.githubusercontent.com/1719237/218615055-4690bc61-75a4-48a7-8596-12c949e71c20.png)

**Comment by zoefried** [comment]
Thanks, it worked!
