### ISSUE TITLE
Inconsistent date on backend and frontend

### ISSUE THREAD

**Issue by msaifuddin** [microfeed/microfeed#51]
I noticed that the post published date are inconsistently displayed between the front end and the back end.

<img width="539" alt="qq" src="https://user-images.githubusercontent.com/1064775/218916450-856f3f30-50e5-4058-9e37-1d1957a8e6b1.png">

Is there a way to fix this and make it consistent on both sides?

**Comment by wenbinf** [comment]
@msaifuddin thanks for reporting the issue!

This should be fixed at https://github.com/microfeed/microfeed/pull/52

Please sync & re-deploy the code.

**Comment by wenbinf** [comment]
Some contexts:

In principle, we use a website visitor's local time everywhere in the browser js code, e.g., time in the "backend" screenshot above.

However, if it's Pages functions code, then microfeed would use the timezone on Cloudflare's edge server, e.g., time in the "frontend" screenshot above. 

This fix https://github.com/microfeed/microfeed/pull/52 is to enforce Cloudflare's edge code to use the timezone of a website visitor.

**Comment by msaifuddin** [comment]
Thanks for the fast fix @wenbinf ! I confirm the issue is resolved.

**Comment by msaifuddin** [comment]
@wenbinf I don't use the RSS feed, but I just noticed this wasn't fixed in the RSS view. FYI.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/1064775/219548395-cb72df24-b096-434a-9da1-ee693a54d171.png">

**Comment by wenbinf** [comment]
the pub date in rss has timezone in the string. that is intentional.
