### ISSUE TITLE
Finished the setup successfully but can't make edit

### ISSUE THREAD

**Issue by ad-astra-via** [microfeed/microfeed#6]
Hi there, finished the set up properly (I think), but I can't make edits. 

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/90049335/209690770-05a27713-c47a-4099-9ca2-5516815872bb.png">

**Comment by jasontally** [comment]
I ended up getting stuck here for a little while too. I had to make sure that the R2 bucket was set for public access and to be sure that I had https:// before the bucket hostname in the field that you highlighted. See the below screenshot where you want to see the green “allowed” in 2 places and the green “active” in one place.

<img width="1264" alt="Screenshot 2022-12-27 at 12 24 08 PM png" src="https://user-images.githubusercontent.com/719178/209701294-56d49515-2237-4dae-9d08-df588672dc68.png">

**Comment by ad-astra-via** [comment]
Yes! that solved it. Thanks so much. If both of us got stuck here, probably worth fixing the docs.

**Comment by wenbinf** [comment]
> Yes! that solved it. Thanks so much. If both of us got stuck here, probably worth fixing the docs.

Definitely we should fix the docs + validate the input in code. 

Thanks!

**Comment by wenbinf** [comment]
This PR should make it less confusing :) https://github.com/microfeed/microfeed/pull/11
