### ISSUE TITLE
Way to host in any other place then CF/Git?

### ISSUE THREAD

**Issue by vdbhb59** [microfeed/microfeed#67]
I like the idea and your implementation. However, is there a way to implement/host this outside of cloudflare/github? Like on a hosting platform, by say placing the code on a site and running from there? It would be helpful and great.

**Comment by wenbinf** [comment]
currently micrifeed runs only on cloudflare.
but it would be definitely more useful to support other platforms.

do you have any target platforms in mind? eg, vercel?

**Comment by vdbhb59** [comment]
I have my hosting on cPanel, shared hosting. Although I do not have root access, I am able to run a lot of OSS and would like to provide this one outside of cloudflare.

**Comment by wenbinf** [comment]
i see.. so you want to run a cms on your own servers 

i would recommend Ghost.org 

microfeed is primarily designed for serverless platforms , starting with Cloudflare. some people (like me) don't want to run & manage servers themselves :)

**Comment by vdbhb59** [comment]
Thanks, but have already tried Ghost few months back and it kind of is resource hungry, especially on cPanel shared ones. Also, is CF/Git not a server kind of logic?

**Comment by wenbinf** [comment]
> Thanks, but have already tried Ghost few months back and it kind of is resource hungry, especially on cPanel shared ones. Also, is CF/Git not a server kind of logic?

No. Using Cloudflare, you don't need to run your own servers. It's serverless.
