### ISSUE TITLE
Cloudflare Access doesn't work with pages.dev

### ISSUE THREAD

**Issue by 10by10pixel** [microfeed/microfeed#70]
Per the [Known Issues](https://community.cloudflare.com/t/disable-route-access-to-cloudflare-pages-via-the-pages-dev-domain/387372) merely adding a Cloudflare Access rule will not prevent one from accessing <NAME>.pages.dev. This needs to be fixed using either a redirect to the custom domain once one is connected or allow the user to switch on enforcement of the JWT. I'd be willing to attempt a pull request once it is determined which approach would cause fewer accidental lockouts. Personally, I've setup a global redirect to enforce my custom domain.

**Comment by wenbinf** [comment]
@10by10pixel yes, there's not an easy / automatic way to allow customer domain access + block .pages.dev access at the same time.

Here's my personal view - 
1. custome-domain.com is public
2. subdomain.page.dev could also be public - as long as you don't leak your Pages project name to the public, this .pages.dev domain won't be accessed. Even people can access to subdomain.pages.dev, I don't think it's a big deal.
3. custom-domain.com/admin should NOT be public
4. subdomain.page.dev/admin should NOT be public
5. *.subdomain.page.dev should NOT be public

3 ~ 5 could be projected by Zero Trust.

**Comment by 10by10pixel** [comment]
This issue is open because I specifically wasn't able to accomplish item 4. Perhaps I'm missing something?

**Comment by wenbinf** [comment]
Let me help you - 

Please follow the order (1, 2, then 3) here on the Zero Trust dashboard:
![image](https://user-images.githubusercontent.com/1719237/232178124-32e2687b-2128-4510-a818-6e8599f6e482.png)

Let me know if you encounter any errors. It would be great if you can share screenshots showing errors.

**Comment by 10by10pixel** [comment]
I do not have my pages.dev subdomain in the dropdown. I only have one Cloudflare account, and the .com domain is in the dropdown.
![image](https://user-images.githubusercontent.com/5394990/233611583-a8311a9d-c456-422b-893a-2bd804156bad.png)
