### ISSUE TITLE
Visual editor "eats" syntax that it doesn't understand

### ISSUE THREAD

**Issue by msarahan** [microfeed/microfeed#79]
Using the HTML editor, I can insert content like https://www.mpking.com/2021/04/making-google-calendar-embeddable.html, with style and div tags.  If I switch back to the visual editor, the style content and the div tags are gone. The iframes inside of the div tags remain, though. Is there any sort of annotation that I can add so that the visual editor will leave particular chunks alone?

**Comment by wenbinf** [comment]
Could you copy and paste the embed code here? Once we have the code here, we (or other people from the Internet) can reproduce the issue and may come up with a fix.

This may be related to the rich editor library we use in microfeed: https://quilljs.com/

Potential solutions:

1) Do research to figure out how to configure quilljs to NOT automatically remove tags/styles

2) Use a new rich editor library to replace quilljs - if you or anyone else knows a good & reliable rich editor library, please comment here

3) This is an open source project - it would be great if anyone wants to take the lead to look at the source code and try to fix it :)

4) If the code you try to insert is used only once, you can use code editor in the settings: https://github.com/microfeed/microfeed/issues/36#issuecomment-1374654227

**Comment by msarahan** [comment]
My apologies for the duplicate issue. I did look, but failed to find it. I don't think there's anything to add to your comment in https://github.com/microfeed/microfeed/issues/36#issuecomment-1374659058:

> So [QuillJs](https://quilljs.com/) (the library we use for rich editor) proactively clean up html to prevent cross site scripting (XSS). We can get around it and allow all html by using quilljs's [dangerouslyPasteHTML](https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml). As the name suggests, it's "dangerous" :)

> We'll need to think through it to make the right trade-offs: 1) security for all users; 2) ease of use for most users; 3) flexibility for tech-savvy power users.

I think your suggestion to use the code editor is the right one for now. I had hoped for a better way, because I'm using this app in a context with code-illiterate people, and I know that the first time any of them edits my about page, my cute responsive google calendar thing will go wonky.

It seems like maybe there is a way to tweak the blot to allow specific attributes (and maybe elements, too?): https://stackoverflow.com/questions/43978105/how-do-you-retain-the-custom-attributes-for-a-paragraph-in-quilljs

I think this might go as a blot formatter in https://github.com/microfeed/microfeed/blob/f01935d5108d318cbed1e02eb44fc140c266525e/client-src/components/AdminRichEditor/component/RichEditorQuill/index.jsx#L27, but I'm not sure. It seems like there may be a layer of abstraction between react-quill and direct usage of quill like the SO post.
