### ISSUE TITLE
Post api call return 201 code but no records.

### ISSUE THREAD

**Issue by postite** [microfeed/microfeed#87]
hello and thanks for this project.
after setting up microfeed, i tried to use teh provided api.
posting via admin is ok 
but i cannot get the api working. the call returns a 201 status with a json id. but there a re no records in the D1. 

see my call made via postman :
<img width="1070" alt="Capture d’écran 2023-07-19 à 16 13 41" src="https://github.com/microfeed/microfeed/assets/834656/95bff6b5-cc2a-4595-ac42-c9a9d1bb93f1">

in cloudflare dashboard i can monitor api calls 

<img width="1067" alt="image" src="https://github.com/microfeed/microfeed/assets/834656/efbe1d42-ec15-464e-8f17-6841c4d81856">

here is  the log:

`
{
  "outcome": "ok",
  "scriptName": "pages-worker--1248874-production",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [],
  "eventTimestamp": 1689776465911,
  "event": {
    "request": {
      "url": "https://62b09bdd.pods-postite-com.pages.dev/api/items/",
      "method": "POST",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "cf-connecting-ip": "78.202.112.102",
        "cf-ipcountry": "FR",
        "cf-ray": "7e939bdfec31d393",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "content-length": "828",
        "content-type": "application/json",
        "host": "62b09bdd.pods-postite-com.pages.dev",
        "postman-token": "REDACTED",
        "user-agent": "PostmanRuntime/7.31.3",
        "x-forwarded-proto": "https",
        "x-microfeedapi-key": "REDACTED",
        "x-real-ip": "78.202.112.102"
      },
      "cf": {
        "clientTcpRtt": 14,
        "longitude": "1.44510",
        "latitude": "43.60460",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "EU",
        "asn": 12322,
        "clientAcceptEncoding": "gzip, deflate, br",
        "country": "FR",
        "isEUCountry": "1",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "168b7fa5952b47eecce2758dbe0e55784814403cecad332ec38952c09d0b09ea",
          "clientHandshake": "c7fc3bd77b7c716568c5b56cdf42fc4f74cf48baefb65467ac2ccf58f0d9687a",
          "serverHandshake": "0e8a40fc6c884c55c101b73be50371316ecc971b4c101af75a0e403dd910a9e7",
          "serverFinished": "16d9cbc287ac314b7b50ec6dd8397915123dd011256603cce4442d543d5fdebe"
        },
        "tlsVersion": "TLSv1.3",
        "city": "Toulouse",
        "timezone": "Europe/Paris",
        "postalCode": "31300",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "",
        "colo": "CDG",
        "httpProtocol": "HTTP/1.1",
        "region": "Occitanie",
        "regionCode": "OCC",
        "asOrganization": "Free SAS",
        "pagesHostName": "62b09bdd.pods-postite-com.pages.dev",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 201
    }
  },
  "id": 0
}
`

same thing with /api/media_files/presigned_urls

what could go wrong ? thx

**Comment by wenbinf** [comment]
Thanks for reporting the bug.

This should be fixed with https://github.com/microfeed/microfeed/pull/88 

Please sync & re-deploy: https://github.com/microfeed/microfeed#bonus-update-to-the-latest-version-of-microfeed

Re:  /api/media_files/presigned_urls
I just tested getting presigned url + uploading files, which worked. Are you able to get presigned url?

**Comment by postite** [comment]
oh ! i realize now i didn't answer . your patch works great !! thx
