### ISSUE TITLE
flac audio file could not be uploaded

### ISSUE THREAD

**Issue by tawayaka** [microfeed/microfeed#96]
I can't upload my flac audio file
![image](https://github.com/microfeed/microfeed/assets/30314539/2c320ee9-e3fd-4c08-9e02-470cd22d33a8)

**Comment by wenbinf** [comment]
You can upload flac audio now: https://github.com/microfeed/microfeed/commit/e2a55e85a7da59f9053d9dab53e566418c548986

Please sync and redeploy your microfeed instance:

![image](https://user-images.githubusercontent.com/1719237/266163087-0c8b75f5-e8e3-4dc8-851f-f5f60d4e3c95.png)
